apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: db_admin
  POSTGRES_PASSWORD: admin_password

  USER_DB_PASSWORD: user_service_user
  EVENT_DB_PASSWORD: event_service_user
  INVENTORY_DB_PASSWORD: inventory_service_user
  BOOKING_DB_PASSWORD: booking_service_user
  PAYMENT_DB_PASSWORD: payment_service_user
  NOTIFICATION_DB_PASSWORD: notification_service_user

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin

---
apiVersion: v1
kind: Secret
metadata:
  name: razorpay-secret
type: Opaque
stringData:
  RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
  RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}

#export RAZORPAY_KEY_ID=rzp_test_xxxxxxxxx
#export RAZORPAY_KEY_SECRET=xxxxxxxxxxxxxxxx
#envsubst < secret.yaml | kubectl apply -f -
