apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: agentveer/payment-service:v2.0.0
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: eventpass-configmap

            - secretRef:
                name: razorpay-secret

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/payment_db

            - name: DB_USERNAME
              value: payment_service_user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PAYMENT_DB_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "300Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service

spec:
  selector:
    app: payment-service

  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085