apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventservice-deployment
  labels:
    app: eventservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      containers:
        - name: eventservice
          image: agentveer/eventservice:v2.0.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: eventpass-configmap
                  key: ACCOUNTS_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: eventpass-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eventpass-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eventpass-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: eventservice
spec:
  selector:
    app: eventservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082