server:
  port: 8089
  forward-headers-strategy: framework

spring:
  application:
    name: 'payment-service'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      enabled: true
      uri: "optional:configserver:http://localhost:8888/"
  config:
    import: optional:configserver:http://localhost:8888/

razorpay:
  key_id: ${RAZORPAYa_KEY_ID}
  key_secret: ${RAZORPAY_KEY_SECRET}
  webhook:
    secret: ${RAZORPAY_WEBHOOK_SECRET} # 7A+so2UBjF3AALPPcmbkaG3ZR7SX/bIkePMDJ3FN4zI=
    event_type: ${RAZORPAY_WEBHOOK_EVENT_TYPE}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost