server:
  port: 8089

spring:
  application:
    name: 'payment-service'

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: booking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    #      properties:
    #        spring.json.trusted.packages: "com.ankit.notification_service.dto"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #      properties:
  #        spring.json.trusted.packages: "com.example.notification-service.dto"

razorpay:
  key_id: ${RAZORPAY_KEY_ID}
  key_secret: ${RAZORPAY_KEY_SECRET}
  webhook:
    secret: ${RAZORPAY_WEBHOOK_SECRET}
    event_type: ${RAZORPAY_WEBHOOK_EVENT_TYPE}