server:
  port: 8089

spring:
  application:
    name: 'payment-service'

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

razorpay:
  key_id: ${RAZORPAY_KEY_ID}
  key_secret: ${RAZORPAY_KEY_SECRET}
  webhook:
    secret: ${RAZORPAY_WEBHOOK_SECRET}
    event_type: ${RAZORPAY_WEBHOOK_EVENT_TYPE}