-- ENUM types
CREATE TYPE user_role AS ENUM ('CONSUMER', 'ORGANIZER', 'ADMIN');

CREATE TABLE IF NOT EXISTS `users` (
    `id` SERIAL PRIMARY KEY,
    `user_id` VARCHAR(100) NOT NULL UNIQUE,
    `first_name` VARCHAR(100) NOT NULL,
    `last_name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `phone_number` VARCHAR(20),
    `avatar_url` VARCHAR(2048),
    `role` user_role DEFAULT 'CONSUMER',
    `is_active` BOOLEAN DEFAULT TRUE,
    `last_login_at` TIMESTAMP WITH TIME ZONE,
    `created_at` TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
