import { Booking, LoyaltyStats } from "../types/bookings";

export const LOYALTY_STATS: LoyaltyStats = {
  points: 70,
  targetPoints: 100,
  attendedCount: 5,
};

export const BOOKINGS_DATA: Booking[] = [
  {
    id: "booking-1",
    title: "Neon Horizon 2024",
    category: "Music",
    status: "confirmed",
    dateText: "Saturday, Oct 12 • 8:00 PM",
    location: "Starlight Amphitheater, Los Angeles",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCEK_8V0Y1KP18N9Nd9esHPhsQRaU5jCOWA6GpnVXU6uyueSnwAZM3JzuIogmZMvGMEK3SIuaN-pDaFrhSyQquu15k5VDiqWWTqzWJFXXJsJCZW2VW1tFnn-OzSVTyzNRBsHakSbXG-P1IuqquLL_fjX5iqsfFUWwvS4TiQTJXuf8e-hTTxT9lzzwGQn0EIW5PMHVwYQz7AzmUkQcGiwifypk0Mddbn5U3mlCNT_Q33fA9du7-hP-kYflCycHkFiVchfYYm6SjRxWL1",
    imageAlt: "Neon Horizon 2024 Music Festival concert stage with neon laser light shows",
    description: "Experience the ultimate electronic dance music concert stage featuring massive LED screens and laser shows.",
    pricePaid: "$125.00",
  },
  {
    id: "booking-2",
    title: "Lakers vs Warriors",
    category: "Sports",
    status: "confirmed",
    dateText: "Nov 05 • 7:30 PM",
    location: "Crypto.com Arena",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDTlCSpjYjo-sE5uDzeRUsy3o2b2vNXCPTykT2X_6GSFF_g_tx1pu2VCHntZYoCEwjncsHXiCYaiqfXdACaHYfVHc3VUZVgKhoqjYHWe9cNKPpxdrjuSkXmF25wvasSf7YZZ0SxKY36-7yRIPl-oCjcbZIQx_0lGW7zay6J1Ay9QSYk98Q2S5o2CqkhJmeyEHkMGaxc9e5uukDyoxUe52yaCBZ0v6jcbhCsBsbtoawZeINpcqaPflZPM7anuO1L3b0-ROg3NIr8kwK7",
    imageAlt: "Brightly lit modern basketball arena court during play",
    description: "Premium lower bowl seating for the classic Western Conference rivalry match.",
    pricePaid: "$240.00",
  },
  {
    id: "booking-3",
    title: "Interstellar: 10th Anniversary",
    category: "Movies",
    status: "completed",
    dateText: "Aug 20 • 6:00 PM",
    location: "Grand Cinema IMAX",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCH3lDCi6ayOv_CehPERnXuuYlwZg9YxjwNkK9FioVK3XIhcTreIMSPSx5Ny6IhtMS8xVKtm50iNaBasltFSxqC8P8qGHztULPnudemU9OyrUyiCcrk648j-7hmwdA_ozXcFoycjaCpCvMfCLMiJ_N35eFAKO1ARxIFMkELWeKOW75H-Bp7LwYeLzPJ9EyoZW1N9e79qubbEjiipNjFLk0v8UpSp-vppUoa9LBPn9Cyce3riF1sHxYpVTOWP5bFdpFWoUDXYmI97fS1",
    imageAlt: "Cinema theater interior screen and plush red velvet seats",
    description: "Special anniversary screening of Christopher Nolan's sci-fi masterpiece in 70mm IMAX.",
    pricePaid: "$22.50",
  },
  {
    id: "booking-4",
    title: "Summer Jazz Night",
    category: "Music",
    status: "cancelled",
    dateText: "Jul 15 • 7:00 PM",
    location: "Blue Note Gardens",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCEK_8V0Y1KP18N9Nd9esHPhsQRaU5jCOWA6GpnVXU6uyueSnwAZM3JzuIogmZMvGMEK3SIuaN-pDaFrhSyQquu15k5VDiqWWTqzWJFXXJsJCZW2VW1tFnn-OzSVTyzNRBsHakSbXG-P1IuqquLL_fjX5iqsfFUWwvS4TiQTJXuf8e-hTTxT9lzzwGQn0EIW5PMHVwYQz7AzmUkQcGiwifypk0Mddbn5U3mlCNT_Q33fA9du7-hP-kYflCycHkFiVchfYYm6SjRxWL1",
    imageAlt: "Outdoor jazz club stage under hanging string lights",
    description: "This event was cancelled by the organizer. A full refund has been processed.",
    pricePaid: "$45.00",
  },
  {
    id: "booking-5",
    title: "Taylor Swift | The Eras Tour",
    category: "Music",
    status: "confirmed",
    dateText: "Dec 18 • 7:00 PM",
    location: "SoFi Stadium, Los Angeles",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCEK_8V0Y1KP18N9Nd9esHPhsQRaU5jCOWA6GpnVXU6uyueSnwAZM3JzuIogmZMvGMEK3SIuaN-pDaFrhSyQquu15k5VDiqWWTqzWJFXXJsJCZW2VW1tFnn-OzSVTyzNRBsHakSbXG-P1IuqquLL_fjX5iqsfFUWwvS4TiQTJXuf8e-hTTxT9lzzwGQn0EIW5PMHVwYQz7AzmUkQcGiwifypk0Mddbn5U3mlCNT_Q33fA9du7-hP-kYflCycHkFiVchfYYm6SjRxWL1",
    imageAlt: "Huge stadium stadium concert with hundreds of spotlights",
    description: "Floor level access ticket for the record-breaking tour.",
    pricePaid: "$350.00",
  },
  {
    id: "booking-6",
    title: "F1 Monaco Grand Prix Screening",
    category: "Sports",
    status: "completed",
    dateText: "May 25 • 2:00 PM",
    location: "EventPass Sports Lounge",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDTlCSpjYjo-sE5uDzeRUsy3o2b2vNXCPTykT2X_6GSFF_g_tx1pu2VCHntZYoCEwjncsHXiCYaiqfXdACaHYfVHc3VUZVgKhoqjYHWe9cNKPpxdrjuSkXmF25wvasSf7YZZ0SxKY36-7yRIPl-oCjcbZIQx_0lGW7zay6J1Ay9QSYk98Q2S5o2CqkhJmeyEHkMGaxc9e5uukDyoxUe52yaCBZ0v6jcbhCsBsbtoawZeINpcqaPflZPM7anuO1L3b0-ROg3NIr8kwK7",
    imageAlt: "Large projector screens showing motor racing inside a bar lounge",
    description: "Cozy group watch party package with food and drink vouchers.",
    pricePaid: "$35.00",
  },
  {
    id: "booking-7",
    title: "Dune: Part Two",
    category: "Movies",
    status: "completed",
    dateText: "Apr 12 • 9:00 PM",
    location: "Grand Cinema IMAX",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCH3lDCi6ayOv_CehPERnXuuYlwZg9YxjwNkK9FioVK3XIhcTreIMSPSx5Ny6IhtMS8xVKtm50iNaBasltFSxqC8P8qGHztULPnudemU9OyrUyiCcrk648j-7hmwdA_ozXcFoycjaCpCvMfCLMiJ_N35eFAKO1ARxIFMkELWeKOW75H-Bp7LwYeLzPJ9EyoZW1N9e79qubbEjiipNjFLk0v8UpSp-vppUoa9LBPn9Cyce3riF1sHxYpVTOWP5bFdpFWoUDXYmI97fS1",
    imageAlt: "IMAX theater screen with epic cinema ambiance",
    description: "Reserved seating in the premium center rows.",
    pricePaid: "$18.50",
  },
  {
    id: "booking-8",
    title: "Rock in Rio 2024",
    category: "Music",
    status: "cancelled",
    dateText: "Sep 15 • 4:00 PM",
    location: "Barra Olympic Park",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCEK_8V0Y1KP18N9Nd9esHPhsQRaU5jCOWA6GpnVXU6uyueSnwAZM3JzuIogmZMvGMEK3SIuaN-pDaFrhSyQquu15k5VDiqWWTqzWJFXXJsJCZW2VW1tFnn-OzSVTyzNRBsHakSbXG-P1IuqquLL_fjX5iqsfFUWwvS4TiQTJXuf8e-hTTxT9lzzwGQn0EIW5PMHVwYQz7AzmUkQcGiwifypk0Mddbn5U3mlCNT_Q33fA9du7-hP-kYflCycHkFiVchfYYm6SjRxWL1",
    imageAlt: "Massive outdoor stadium festival venue during daylight",
    description: "General admission weekend ticket. Refunded due to scheduling conflict cancellation.",
    pricePaid: "$220.00",
  }
];
