server:
  port: 8888

spring:
  application:
    name: 'config-server'

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/1820ANKIT2029/Event-Ticketing-System-Config.git"
          search-paths:
            - common
            - gateway-server
            - eureka-server
            - user-service
            - event-service
            - venue-service
            - booking-service
            - payment-service
            - notification-service
            - search-service
            - analytics-service
          default-label: main
          timeout: 60
          clone-on-start: true
#          skip-ssl-validation: true
          force-pull: true
        native:
          search-locations: file:///C:/Users/Ankit/Downloads/Event-Ticketing-System-Config/common
    bus:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      observation-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG